package euro.milhoes.app;

import java.io.Serializable;

/**
 * Pair.java
 * Purpose: Declaration of the Object Pair, which contains a number 
 * and the number of times that number appeard in all EuroMillions draws.
 *
 * @author Bruno Ferreira
 * @version 1.10 8/11/11
 */
//date format: mm/dd/yy
/* I implmented Comparable 'cause there's need to define that if 
 * number x appeard more times (greater frequency) than number y, then number x 
 * is greater then y. This is usefull 'cause we use Pairs in TreeSets,so we had to redefine 
 * the "compareTo" method.
 * I also implemented Serializable cause we need to write and load Pairs to and from a file
 * to mantain a state of the application, so we had to implement it too.*/
public class Pair implements Comparable<Pair>, Serializable{
	private static final long serialVersionUID = 1L; //Id generated by Serializable
	final public int num; //the number
	public int freq; // the number of times that a number appeard
	
	/**
	 * Constructor of a Pair given two ints, a number and the number of times it appeard
	 * */
	public Pair(int num, int freq){
		this.num = num;
		this.freq = freq;
	}

	/**
	 * Method to return frequency (number of times a number appeard).
	 * */
	public int getFreq(Pair p){
		return p.freq;
	}
	/**
	 * Method to return a number of a given Pair.*/
	public int getNum(Pair p){
		return p.num;
	}

	@Override
	public int compareTo(Pair p) {//Method to compare two Pairs
		if(getFreq(p)>getFreq(this)){ //if the freq of p is greater, p is greater than "this"
			return 1;
		}
		else if(p.equals(this)){//if they+re equal, we return 0
			return 0;
		}else{//and for everything else we return -1
			return -1;
		}
	}	
	
	@Override
	public String toString(){
		return getNum(this) + " = " + getFreq(this);
	}

	@Override
	public boolean equals (Object o){
		Pair p = (Pair) o;
		if((getFreq(p)==getFreq(this) && getNum(p) == getNum(this))){
			return true;
		}else{
			return false;
		}
	}
}